// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBckgbUx6MxfOCxg1V-clDBQMuFu9Xww9Y',
    appId: '1:1051749831627:web:35eb3fc276518b987b1c4e',
    messagingSenderId: '1051749831627',
    projectId: 'si700-84afe',
    authDomain: 'si700-84afe.firebaseapp.com',
    databaseURL: 'https://si700-84afe-default-rtdb.firebaseio.com',
    storageBucket: 'si700-84afe.appspot.com',
    measurementId: 'G-RD7P78PD3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtJo69mJKbmG1pKB15mqSmWtleN22D6w',
    appId: '1:1051749831627:android:0b64e38ac11579877b1c4e',
    messagingSenderId: '1051749831627',
    projectId: 'si700-84afe',
    databaseURL: 'https://si700-84afe-default-rtdb.firebaseio.com',
    storageBucket: 'si700-84afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Kfmhua6-6aByAOZN81WOD7O8NXemRPc',
    appId: '1:1051749831627:ios:d7c1d865ab37b9417b1c4e',
    messagingSenderId: '1051749831627',
    projectId: 'si700-84afe',
    databaseURL: 'https://si700-84afe-default-rtdb.firebaseio.com',
    storageBucket: 'si700-84afe.appspot.com',
    iosBundleId: 'com.example.atividade2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Kfmhua6-6aByAOZN81WOD7O8NXemRPc',
    appId: '1:1051749831627:ios:767569af984c148d7b1c4e',
    messagingSenderId: '1051749831627',
    projectId: 'si700-84afe',
    databaseURL: 'https://si700-84afe-default-rtdb.firebaseio.com',
    storageBucket: 'si700-84afe.appspot.com',
    iosBundleId: 'com.example.atividade2.RunnerTests',
  );
}